### ISSUE TITLE
QS about RNIM  dataset

### ISSUE THREAD

**Issue by Jemmagu** [rpautrat/LISRD#1]
Hi @rpautrat ,

thanks for your great work! I wanna ask will you release the code evaluating on RNIM dataset, big thanks!

**Comment by rpautrat** [comment]
Hi @Jemmagu,

It is not planned to release it for now as it requires some maintenance to make it usable for everyone. But I may work on a light evaluation pipeline to reproduce the results and allow comparison to any other method in the future. Probably not before September though.

**Comment by Jemmagu** [comment]
Hi @rpautrat ,
okay, thanks!
I have another question about your work. Will you focus on a complete localization pipeline in the future? Or you might think currently a SOTA keypoint detector + your descriptor would be great enough (disentangle keypoints detector and descriptor is quite ok) ? 

Thanks again.

**Comment by rpautrat** [comment]
Hi,
For now I have no plan to integrate the same idea as LISRD in a full localization pipeline. The idea is quite transversal to previous research on descriptors, so that you can use LISRD with any SOTA keypoint detector and custom matcher and directly integrate it in an existing localization pipeline.

**Comment by Jemmagu** [comment]
Hi @rpautrat ,
I tested your matching pipeline ( the provided notebook) using Hpatches images pairs, however the result really confused me. As to the day-day pairs or night-night pairs, it performs great. However, when it comes to day-night pairs, the matching results seems very disappointing. I can't figure out the reason. Can you explain it, maybe there's something with my test precedure or it might be LISRD model's problem?

Thanks in advance, looking forward to your reply!

**Comment by rpautrat** [comment]
Hi,
The illumination invariant descriptor is still trained according to a similar procedure as previous learned descriptors (e.g. SuperPoint), so it is still not able to cope with too challenging day-night changes. I guess that the examples you tried were too hard for LISRD. The benefit of LISRD is mainly to bring a boost of performance when the illumination (or rotation) is changing a lot and helps keep discriminative descriptors even when invariance is not needed. But it doesn't necessarily perform better than other learned descriptors on purely day-night changes.

**Comment by Jemmagu** [comment]
Hi @rpautrat ,
but I tried the day-night pairs showed in your paper ( folder 00003837 of the RDNIM dataset). I used the sift+lisrd just as mentioned in your notebook, and compared it with your result; however my matching result is quite disappointing ( but yours is great). And when it comes to other day-day pairs (eg. i_fog folder of Hpatches dataset) / night-night pairs, my matching result is as good as yours. That's what really confused me. 

Really hope to get your reply. Big thanks!

**Comment by rpautrat** [comment]
Hi,
Are you also using the pretrained weights lisrd_vidit as in the notebooks? I think that when I tried the other day-night pairs of this folder, only a few of them were working great like the one in the notebooks. Most of the others were mainly failing, so I think that it is what you observed. Once again, when the day-night changes are too strong, the method doesn't work so well.

**Comment by Jemmagu** [comment]
Hi @rpautrat ,
yes, i used the lisrd_vidit as in the notebooks. I tried exactly the same day-night pair in folder 00003837 of the RDNIM dataset, but my sift+lisrd performs much worse than you showed, however the easy pairs matched correctly (so I think the matching process should be okay with no bug). And I ploted the MMA curve of Hpatch, sp+lisrd performs bad. Not sure it's my problem or what else...quite confused.

**Comment by rpautrat** [comment]
Hi,
The matches (and all results) shown in the paper were obtained with the initial set of weights lisrd_aachen.pth. Overall, for the difficult day-night pairs, LISRD was not always working and it is normal to still observe failure cases.
As for the MMA curve of HPatches, I will probably release in 1-2 weeks an evaluation code to reproduce similar results as in the paper. But sp+lisrd should be the best combination overall, so I am surprised that you got poor results.

**Comment by rpautrat** [comment]
Hi @Jemmagu,
After a bit of delay, I finally released the evaluation code on the RDNIM dataset. You can now test it and compare it with your own evaluation that seemed to perform poorly for LISRD. Let me know if you spot anything wrong in the release!
