### ISSUE TITLE
Hi, I have a problem converting LISRD to ONNX

### ISSUE THREAD

**Issue by yeluoo** [rpautrat/LISRD#17]
LISRD2ONNX
Problem 1:   TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (h % tile != 0) or (w % tile != 0):  # should be divisible by tile
First check is not problem
ONNX2NCCN
Problem 2: 
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unknown data type 0
Expand not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Equal not supported yet!
Where not supported yet!
Expand not supported yet!
Unsupported unsqueeze axes !
Shape not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unknown data type 0
Expand not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Equal not supported yet!
Where not supported yet!
Expand not supported yet!
Unsupported unsqueeze axes !
Shape not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unknown data type 0
Expand not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Equal not supported yet!
Where not supported yet!
Expand not supported yet!
Unsupported unsqueeze axes !
Shape not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unknown data type 0
Expand not supported yet!
Shape not supported yet!

**Comment by rpautrat** [comment]
Hi, I don't have experience with converting a model to ONXX, so I think you need to resolve these issues by yourself. They seem to be pretty general ones, so other people certainly already had similar ones in the past.
