### ISSUE TITLE
Code covert c++

### ISSUE THREAD

**Issue by ChmarsLuo** [rpautrat/LISRD#19]
Hello, thank you very much for your code, can you convert the post-processing part of your code into C++, I have encountered many problems and there is no way to solve them.

**Comment by rpautrat** [comment]
Hi, what do you mean by postprocessing part? You mean allowing to do an inference of LISRD in C++? I am sorry, but I can't do that.

If you have problems with Python, you mention them here and we can try to find a solution.

**Comment by ChmarsLuo** [comment]
thanks
