### ISSUE TITLE
About model lisrd_sift

### ISSUE THREAD

**Issue by heiya07** [rpautrat/LISRD#22]
Thank you very much for the code and models.I encountered a problem when using the lisrd_sift option.

  File "g:/project/3d/LISRD-master/lisrd/export_features.py", line 88, in export
    func.grid_sample(torch.Tensor(descs[k]), grid_points),
  File "C:\Users\Administrator\anaconda3\lib\site-packages\torch\nn\functional.py", line 4304, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected grid to have size 1 in last dimension, but got grid with sizes [1, 2000, 1, 2]

How can I solve this issue?
Looking forward to your replay

**Comment by rpautrat** [comment]
Hi, the export of features was not compatible with LISRD-SIFT. I pushed a fix to make it compatible. It should work now, but feel free to reopen the issue if it does not.

**Comment by heiya07** [comment]
Thank you for your reply. It can be work now, But I encountered some problems while matching,Please help to complete the match module based on the lisrd_sift .Currently, the extracteddescriptors and lisrd_matcher functions do not support lisrd_sift.
Thank you again, looking forward to your reply .
