### ISSUE TITLE
Using pretrained models

### ISSUE THREAD

**Issue by BruceWANGDi** [rpautrat/LISRD#6]
Hi, I am a freshman to this field, and I prepare using the pretrained model to see your work's result on my own images. Therefore, whether I needn't training my own model? Could you give an advice about how to use the command?
"python -m lisrd.export_features <path to a txt file listing all your images> <name of the model (lisrd or lisrd_sift)> --checkpoint <path to checkpoint> --keypoints <type of keypoints (sift or superpoint)> --num_kp <number of keypoints (default: 2000)>"
I haven't found any file or folder named checkpoint, how can I get this file?

**Comment by BruceWANGDi** [comment]
Thank you for your sharing. I get the folder named 'checkpoint' after I run the command "python -m lisrd.experiment train lisrd/configs/lisrd.yaml ~/Documents/experiments/My_experiment", but there is nothing in this folder '/My_experiment/checkpoint/. When I run this command, it prompts an error "No module named 'lisrd.third_party.super_point_magic_leap.demo_superpoint' "
How can I solve this issue?
Looking forward to your replay.

**Comment by rpautrat** [comment]
Hi,

If you just want to run the model to see the results, please have a look at the notebook https://github.com/rpautrat/LISRD/blob/master/notebooks/demo_lisrd.ipynb. It shows how to use the pretrained weights available in https://github.com/rpautrat/LISRD/tree/master/weights.

In case you want to retrain the model, your second command is correct, but you may not have followed the instruction of the Readme to clone the repository:
```git clone --recurse-submodules https://github.com/rpautrat/LISRD.git```
Alternatively, you can also run the following command in your already cloned repo:
```git submodule update --init --recursive```

**Comment by BruceWANGDi** [comment]
@rpautrat Hi,
I ran the demo successfully! Thank you soooooo~ much, I'm so exciting!!!
But there is an another question, the result I run shows just few matching lines. How can I get more matching lines?

**Comment by rpautrat** [comment]
Hi,
Great! The number of matching lines will depend on the complexity of the images to match that you use. The more illumination and viewpoint changes there are, the harder it will be to find matches.

**Comment by BruceWANGDi** [comment]
Thank you for your reply. Your advices help me a lot.

**Comment by BruceWANGDi** [comment]
@rpautrat 
I'm sorry to disturb you again. When I run the 'demo_lisrd.py' with my own images, there is an issue that both endpoints of every matching lines can not correspond to the extracted key points.
Could you tell me how to solve this issue? Thanks a lot.

**Comment by rpautrat** [comment]
Hi, could you give an example of your matches?
Are you using the right convention for the keypoints? When using the functions `plot_keypoints` and `plot_matches`, they should be in xy coordinates (column first, then row). Maybe that is the cause of your issue.

**Comment by BruceWANGDi** [comment]
Hi, I haven't revised any code in 'demo_lisrd.py'.
I just change the images in the path: '../assets/rdnim_samples/*.jpg'.
You mean that I need revise the following codes?
'plot_keypoints([kp1[:, [1, 0]], kp2[:, [1, 0]]], colors='blue', ps=5)
plot_matches(matched_kp1, matched_kp2, color='lime', lw=1)'
Or I need revise and rerun some code in folder utils' functions?

**Comment by BruceWANGDi** [comment]
Sorry to bother you so long because of the simple question. I find the reason why this issue happened. It is just that I enlarge the result image, so that the matching lines have a wrong display.
