### ISSUE TITLE
why swap the x,y order after we get keypoint?

### ISSUE THREAD

**Issue by captainfffsama** [rpautrat/LISRD#8]
I feel confused about that in`keypoint_detectors.py` [line 14](https://github.com/rpautrat/LISRD/blob/0686fdebc0c3f5ec46b073e0d8b0d3f64a2ba1d1/lisrd/models/keypoint_detectors.py#L14) and [line 22](https://github.com/rpautrat/LISRD/blob/0686fdebc0c3f5ec46b073e0d8b0d3f64a2ba1d1/lisrd/models/keypoint_detectors.py#L22) ,you just change keypoint x,y order as y,x,  is there any significance in doing this?

Thx for u brilliant work and looking forward to your reply

**Comment by rpautrat** [comment]
Hi,
It is just a matter of convention. The SIFT OpenCV and original SuperPoint give the keypoint coordinates in (x, y) format, whereas I prefer using them in (row, column) coordinates, which is more natural when dealing with Python matrices. The swap of x, y into y, x thus represents this conversion.
